CREATE TABLE ADMINISTRADOR (
  ADM_ID INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  ADM_USUARIO VARCHAR(45) NOT NULL,
  ADM_NOME VARCHAR(45) NOT NULL,
  ADM_EMAIL VARCHAR(45) NOT NULL,
  ADM_SENHA VARCHAR(45) NOT NULL,
  PRIMARY KEY(ADM_ID)
);

CREATE TABLE DESAPARECIDO (
  DES_ID INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  ENCONTRADO_ENC_ID INTEGER UNSIGNED NOT NULL,
  ADMINISTRADOR_ADM_ID INTEGER UNSIGNED NOT NULL,
  DES_ADM_ID INTEGER UNSIGNED NOT NULL,
  DES_NOME VARCHAR(45) NOT NULL,
  DES_SOBRENOME VARCHAR(45) NOT NULL,
  DES_LOCAL_DESAPARECIMENTO VARCHAR(255) NOT NULL,
  DES_DATA_DESAPARECIMENTO DATE NOT NULL,
  PRIMARY KEY(DES_ID),
  INDEX Desaparecido_FKIndex1(ADMINISTRADOR_ADM_ID),
  INDEX DESAPARECIDO_FKIndex2(ENCONTRADO_ENC_ID)
);

CREATE TABLE ENCONTRADO (
  ENC_ID INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  VISITANTE_VIS_ID INTEGER UNSIGNED NOT NULL,
  ENC_RESPONSAVEL INTEGER UNSIGNED NOT NULL,
  ENC_DESC VARCHAR(255) NOT NULL,
  ENC_DATA DATE NOT NULL,
  PRIMARY KEY(ENC_ID),
  INDEX ENCONTRADO_FKIndex1(VISITANTE_VIS_ID)
);

CREATE TABLE INFORMACAO (
  INFO_ID INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  INFO_MENSAGEM VARCHAR(255) NOT NULL,
  INFO_LOCAL VARCHAR(45) NOT NULL,
  INFO_DATA DATE NOT NULL,
  PRIMARY KEY(INFO_ID)
);

CREATE TABLE VISITANTE (
  VIS_ID INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  INFORMACAO_INFO_ID INTEGER UNSIGNED NOT NULL,
  VIS_NOME VARCHAR(45) NOT NULL,
  VIS_EMAIL VARCHAR(45) NOT NULL,
  VIS_MENSAGEM VARCHAR(255) NOT NULL,
  VIS_DATA DATE NOT NULL,
  PRIMARY KEY(VIS_ID),
  INDEX VISITANTE_FKIndex1(INFORMACAO_INFO_ID)
);


